/*
 * V$-GOIN API
 *
 * This is the official API for the interaction with the VS-Blockchain. This API focuses on payment-related use cases in the most easy and feasible way. All relevant keys and parameters are documented directly within the schema definitions.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api_adapter

import (
	"github.com/gin-gonic/gin"
)

type KeyToolsAPI struct {
}

// Get /address
// Returns the V$Address to a corresponding private key.
func (api *KeyToolsAPI) AddressGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /address/new
// Returns a new V$Address with the corresponding private key.
func (api *KeyToolsAPI) AddressNewGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}
