/*
 * V$-GOIN API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api_adapter

import (
	"github.com/gin-gonic/gin"
)

type PaymentAPI struct {
}

// Get /balance
// Returns the balance tied to the given public key hash
func (api *PaymentAPI) BalanceGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /history
// Returns the history of transactions involving the given key hash
func (api *PaymentAPI) HistoryGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /transaction
// Executes a transaction
func (api *PaymentAPI) TransactionPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}
