/*
 * V$-GOIN API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api_adapter

import (
	"github.com/gin-gonic/gin"
)

type KeyToolsAPI struct {
}

// Get /address
// Returns the V$Address to a corresponding private key.
func (api *KeyToolsAPI) AddressGet(c *gin.Context) {
	// Your handler implementation
	println(c.GetHeader("privateKey"))
	c.JSON(200, AddressGet200Response{VSAddress: "hee"})
	//c.JSON(200, gin.H{"status": "OK"})
}

// Get /address/new
// Returns a new V$Address with the corresponding private key.
func (api *KeyToolsAPI) AddressNewGet(c *gin.Context) {
	println("hallo")
	c.JSON(200, gin.H{"status": "OK"})
}
