/*
 * V$-GOIN API
 *
 * This is the official API for the interaction with the VS-Blockchain. This API focuses on payment-related use cases in the most easy and feasible way. All relevant keys and parameters are documented directly within the schema definitions.
 *
 * API version: 1.0.0
 * Base Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api_adapter

import (
	"s3b/vsp-blockchain/rest-api/konto"

	"github.com/gin-gonic/gin"
)

type KeyToolsAPI struct {
	kontostand konto.Kontostand
}

func NewKeyToolsAPI(kontostand konto.Kontostand) *KeyToolsAPI {
	return &KeyToolsAPI{
		kontostand: kontostand,
	}
}

// Get /address
// Returns the V$Address to a corresponding private key.
func (api *KeyToolsAPI) AddressGet(c *gin.Context) {
	// Your handler implementation
	keyset, err := api.kontostand.GetKeysetFromWIF(c.GetHeader("privateKeyWIF"))

	if err != nil {
		c.JSON(400, gin.H{
			"error": "private Key is not Valid",
		})
		return
	}

	response := AddressGet200Response{
		VSAddress: keyset.VSAddress,
	}

	c.JSON(200, response)
}

// Get /address/new
// Returns a new V$Address with the corresponding private key.
func (api *KeyToolsAPI) AddressNewGet(c *gin.Context) {
	keyset := api.kontostand.GenerateKeyset()

	response := AddressNewGet200Response{
		NewPrivateKeyWIF: keyset.PrivateKeyWif,
		NewVSAddress:     keyset.VSAddress,
	}

	c.JSON(200, response)
}
