/*
 * V$-GOIN API
 *
 * This is the official API for the interaction with the VS-Blockchain. This API focuses on payment-related use cases in the most easy and feasible way. All relevant keys and parameters are documented directly within the schema definitions.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
	"s3b/vsp-blockchain/rest-api/internal/common"
	transactionapi "s3b/vsp-blockchain/rest-api/transaktion"

	"github.com/gin-gonic/gin"
)

type DevToolsAPI struct {
	transactionService *transactionapi.TransaktionAPI
}

func NewDevToolsAPI(transactionService *transactionapi.TransaktionAPI) *DevToolsAPI {
	return &DevToolsAPI{
		transactionService: transactionService,
	}
}

// Get /blockchain/visualization
// Returns a URL to the visualization of the current blockchain.
func (api *DevToolsAPI) BlockchainVisualizationGet(c *gin.Context) {

	url, err := api.transactionService.GetBlockchainVisualization()

	if err != nil {
		if errors.Is(err, common.ErrServer) {
			c.JSON(500, gin.H{
				"error": err.Error(),
			})
			return
		}
		c.JSON(500, gin.H{
			"error": "unknown error",
		})
		return

	}

	response := BlockchainVisualizationGet200Response{
		URL: url,
	}

	c.JSON(200, response)
}
