/*
 * V$-GOIN API
 *
 * This is the official API for the interaction with the VS-Blockchain. This API focuses on payment-related use cases in the most easy and feasible way. All relevant keys and parameters are documented directly within the schema definitions.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type HistoryGet200Response struct {
	Transactions []string `json:"transactions,omitempty"`
}
