/*
 * V$-GOIN API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api_adapter

type AddressNewGet200Response struct {

	// Base58Check-encoded public key hash.
	NewVSAddress string `json:"newVSAddress,omitempty"`

	// Base58Check-encoded private key
	NewPrivateKey string `json:"newPrivateKey,omitempty" validate:"regexp=^5[1-9A-HJ-NP-Za-km-z]{50}$"`
}
