/*
 * V$-GOIN API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api_adapter

type AddressGet200Response struct {

	// Base58Check-encoded public key hash.
	VSAddress string `json:"VSAddress"`
}
