/*
 * V$-GOIN API
 *
 * This is the official API for the interaction with the VS-Blockchain. This API focuses on payment-related use cases in the most easy and feasible way. All relevant keys and parameters are documented directly within the schema definitions.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AddressGet200Response struct {

	// Base58Check-encoded compressed PublicKeyHash with 0x00 as prefix. Has a length of 33 or 34 characters.  The VSAddress provides a point where VSGoins can be send to. It is public and can be freely shared with others.  Way to generate a PublicKey 1. Use the equation K = k * G   - K is the PublicKey (with two points x,y)   - k is the PrivateKey   - G is the generator point defined in the secp256k1 standard   - * denotes scalar multiplication on the elliptic curve  Way to generate a compressed PublicKey 1. get x-coordinate from the PublicKey 2. if the y-coordinate from the Public key is even, the prefix is 0x02, otherwise it is 0x03 3. the compressed PublicKey is the prefix followed by the x-coordinate  -> (the y-coordinate can afterwards easily be calculated with y^2 mod p = (x^3 + 7))  Way to generate a compressed PublicKeyHash 1. Create a SHA 256 the compressed PublicKey 2. Create a SHA 256 of the result 3. the first 160 bits are the compressed PublicKeyHash
	VSAddress string `json:"VSAddress"`
}
