/*
 * V$-GOIN API
 *
 * This is the official API for the interaction with the VS-Blockchain. This API focuses on payment-related use cases in the most easy and feasible way. All relevant keys and parameters are documented directly within the schema definitions.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the DevToolsAPI part of the API
	DevToolsAPI DevToolsAPI
	// Routes for the KeyToolsAPI part of the API
	KeyToolsAPI KeyToolsAPI
	// Routes for the PaymentAPI part of the API
	PaymentAPI PaymentAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{
		{
			"BlockchainVisualizationGet",
			http.MethodGet,
			"/blockchain/visualization",
			handleFunctions.DevToolsAPI.BlockchainVisualizationGet,
		},
		{
			"AddressGet",
			http.MethodGet,
			"/address",
			handleFunctions.KeyToolsAPI.AddressGet,
		},
		{
			"AddressPost",
			http.MethodPost,
			"/address",
			handleFunctions.KeyToolsAPI.AddressPost,
		},
		{
			"BalanceGet",
			http.MethodGet,
			"/balance",
			handleFunctions.PaymentAPI.BalanceGet,
		},
		{
			"HistoryGet",
			http.MethodGet,
			"/history",
			handleFunctions.PaymentAPI.HistoryGet,
		},
		{
			"TransactionPost",
			http.MethodPost,
			"/transaction",
			handleFunctions.PaymentAPI.TransactionPost,
		},
	}
}
