name: Setup
author: bennet
description: Sets up the project, by checking out the code and installing necessary tools
runs:
  using: composite
  steps:
    - name: Check out code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: Generate protos
      uses: ./.github/actions/generate_grpc
      with:
        protoc_version: '33.0'