kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: access-for-vsp-blockchain
    namespace: vsp-blockchain
subjects:
    - kind: User
      name: wqx847
    - kind: User
      name: wwv166
    - kind: User
      name: wxv415
roleRef:
    kind: Role
    name: hnc-user-default
    apiGroup: rbac.authorization.k8s.io
