apiVersion: apps/v1
kind: Deployment
metadata:
    name: rest-api
    namespace: vsp-blockchain
spec:
    replicas: 1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 0
            maxUnavailable: 1
    selector:
        matchLabels:
            app: rest-api
    template:
        metadata:
            labels:
                app: rest-api
        spec:
            dnsPolicy: None
            dnsConfig:
                nameservers:
                    - 10.233.1.72
                searches:
                    - vsp-blockchain.svc.k8s.informatik.haw-hamburg.de
                    - svc.k8s.informatik.haw-hamburg.de
                    - k8s.informatik.haw-hamburg.de
                    - default.svc.k8s.informatik.haw-hamburg.de
                    - icc.informatik.haw-hamburg.de
            containers:
                - name: spv
                  image: ghcr.io/bjoern621/vsp-blockchain-miner:latest
                  imagePullPolicy: Always
                  env:
                      - name: APP_PORT
                        value: "50050"
                      - name: P2P_PORT
                        value: "50051"
                      - name: APP_LISTEN_ADDR
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      - name: P2P_LISTEN_ADDR
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      - name: ADDITIONAL_SERVICES
                        value: "wallet, blockchain_simple, app"
                  ports:
                      - name: app
                        containerPort: 50050
                        protocol: TCP
                      - name: p2p
                        containerPort: 50051
                        protocol: TCP
                  resources:
                      requests:
                          cpu: "50m"
                          memory: "64Mi"
                      limits:
                          cpu: "200m"
                          memory: "128Mi"
                - name: rest-api
                  image: ghcr.io/bjoern621/vsp-blockchain-rest-api:latest
                  imagePullPolicy: Always
                  env:
                      - name: APP_GRPC_ADDR_PORT
                        value: "127.0.0.1:50050"
                  ports:
                      - containerPort: 8080
                  resources:
                      requests:
                          cpu: "50m"
                          memory: "64Mi"
                      limits:
                          cpu: "200m"
                          memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
    name: rest-api-service
    namespace: vsp-blockchain
spec:
    type: LoadBalancer
    selector:
        app: rest-api
    ports:
        - port: 8080
          targetPort: 8080
