version: "3"

includes:
    rest:
        taskfile: ./rest-schnittstelle/Taskfile.yml
        dir: ./rest-schnittstelle
    miner:
        taskfile: ./p2p-blockchain/Taskfile.yml
        dir: ./p2p-blockchain
    registry-crawler:
        taskfile: ./registry-crawler/Taskfile.yml
        dir: ./registry-crawler

vars:
    NAMESPACE: vsp-blockchain
    DOCKER_TAG: latest

tasks:
    deploy:
        desc: Deploy to current Kubernetes context
        cmds:
            - task: rest:build
            - task: miner:build
            - task: clean
            - task: k8s-deploy

    clean:
        desc: Delete Kubernetes deployment
        cmds:
            - kubectl delete namespace {{.NAMESPACE}} --ignore-not-found=true

    k8s-deploy:
        internal: true
        cmds:
            - kubectl apply -f kubernetes-deployment-local.yaml

    up:
        desc: Start local docker-compose stack (miners, seed-dns registry, crawler, rest-api)
        cmds:
            - task: rest:prepare
            - task: miner:prepare
            - task: registry-crawler:prepare
            - docker compose -f docker-compose.local.yaml up --build -d

    down:
        desc: Stop local docker-compose stack
        cmds:
            - docker compose -f docker-compose.local.yaml down -v
