/*
 * V$-GOIN API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BalanceGet200Response struct {
	Balance int32 `json:"balance,omitempty"`
}
