/*
 * V$-GOIN API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TransactionPostRequest struct {

	// Base58Check-encoded public key hash.
	RecipientVSAddress string `json:"recipientVSAddress"`

	// The amount of V$-Goin the sender wants to transfer
	Amount int32 `json:"amount"`

	// Base58Check-encoded private key
	SenderPrivateKey string `json:"senderPrivateKey" validate:"regexp=^5[1-9A-HJ-NP-Za-km-z]{50}$"`
}
