version: "3"

vars:
    DOCKER_TAG: latest

tasks:
    tidy:
        internal: true
        desc: Run go mod tidy
        cmds:
            - go mod tidy

    proto:
        desc: Generate gRPC code from shared and local .proto files
        dir: ..
        cmds:
            - buf generate

    prepare:
        desc: Prepare the module for build
        cmds:
            - task: proto
            - task: tidy

    build:
        desc: Build the docker image for p2p-miner
        cmds:
            - task: prepare
            - docker build -t vsp-blockchain/miner:{{.DOCKER_TAG}} .
