@startuml
node HAW-ICC <<Environment>> {
    component "Mining System" as system {
        component "Registry" as registry <<Service>>
        component "P2P Netzwerk" as p2p_network <<Service>>
    }
}
@enduml
