@startuml
rectangle "P2P Netzwerk" as p2p_network {
    collections "SPV-Node" as spv
    component "Registry Crawler" as crawler
    
    collections "Full-Node" as full_node
}

crawler <-> spv :"P2P Nachrichten"
crawler <-> full_node :"P2P Nachrichten"
spv <-> full_node :"P2P Nachrichten"


@enduml
