name: install_generate_grpc
author: bennet
description: "Installs protoc and the go packages to generate stubs and generates stubs"
inputs:
  protoc_version:
    description: "protoc version"
    required: false
    default: "33.0"
  generation_folder:
    description: "The folder, where the stubs will be generated"
    required: false
    default: "./generated"
runs:
  using: composite
  steps:
    - name: Install protoc
      shell: bash
      run: |
        curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v${{ inputs.protoc_version }}/protoc-${{ inputs.protoc_version }}-linux-x86_64.zip
        sudo apt-get install -y unzip
        unzip -o protoc-${{ inputs.protoc_version }}-linux-x86_64.zip -d $HOME/.local
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install protoc Go plugins
      shell: bash
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Generate Go protobuf stubs
      shell: bash
      run: |
        mkdir -p ${{ inputs.generation_folder }}
        for file in $(find . -name "*.proto"); do
          protoc \
            --proto_path=. \
            --go_out=${{ inputs.generation_folder }} --go_opt=paths=source_relative \
            --go-grpc_out=${{ inputs.generation_folder }} --go-grpc_opt=paths=source_relative \
            $file
        done