name: go-ci
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

permissions:
  contents: read
  pull-requests: read
  packages: write

jobs:
  build-and-test:
    name: "Build, Lint and test"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Check formatting
        uses: ./.github/actions/check_go_formatting

      - name: Install protoc
        uses: ./.github/actions/install_generate_grpc
        with:
          protoc_version: '33.0'

      - name: Check linting
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=3m

      - name: Run tests
        run: |
          go test -v ./...

      - name: Build app
        run: go build -v ./...

      - name: "Login"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/vsp-blockchain:latest